Update index.rst
CiscoTestAutomation/genie pull request #52
Opened 2021-09-29 20:10 UTC by GerriorL

2021-09-30 11:03 UTC, tahigash requested changes

2021-09-30 11:03 UTC, tahigash commented on docs/changelog/index.rst
> +   2021/september
where is `september.rst`?

2021-10-01 18:29 UTC, ThomasJRyan approved these changes

2021-10-01 18:39 UTC, tahigash approved these changes

2021-10-01 18:39 UTC, merged